namespace DUTAdmissionSystem.Database.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddRequiredForEntities : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Account", "UserInfoId", "dbo.UserInfo");
            DropForeignKey("dbo.Student", "UserInfoId", "dbo.UserInfo");
            DropForeignKey("dbo.Family", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Achievement", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "ClassId", "dbo.Class");
            DropForeignKey("dbo.Document", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "EnrollmentAreaId", "dbo.EnrollmentArea");
            DropForeignKey("dbo.HighSchoolResult", "StudentId", "dbo.Student");
            DropForeignKey("dbo.HightSchoolPosition", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Insurance", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "PersonalInfoId", "dbo.PersonalInfo");
            DropForeignKey("dbo.Talent", "StudentId", "dbo.Student");
            DropForeignKey("dbo.UniversityExamResult", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Class", "DepartmentId", "dbo.Department");
            DropForeignKey("dbo.Class", "ProgramId", "dbo.Program");
            DropForeignKey("dbo.Department", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Document", "DocumentTypeId", "dbo.DocumentType");
            DropForeignKey("dbo.HighSchoolResult", "ConductTypeId", "dbo.ConductType");
            DropForeignKey("dbo.HighSchoolResult", "HightSchoolYearId", "dbo.HightSchoolYear");
            DropForeignKey("dbo.HighSchoolResult", "LearningAbilityId", "dbo.LearningAbility");
            DropForeignKey("dbo.HightSchoolPosition", "PositionTypeId", "dbo.PositionType");
            DropForeignKey("dbo.Insurance", "InsuranceTypeId", "dbo.InsuranceType");
            DropForeignKey("dbo.PersonalInfo", "EthnicId", "dbo.Ethnic");
            DropForeignKey("dbo.PersonalInfo", "NationalityId", "dbo.Nationality");
            DropForeignKey("dbo.PersonalInfo", "ReligionId", "dbo.Religion");
            DropForeignKey("dbo.Talent", "TalentTypeId", "dbo.TalentType");
            DropForeignKey("dbo.UniversityExamResult", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.Permission", "FunctionInScreenId", "dbo.FunctionInScreen");
            DropForeignKey("dbo.FunctionInScreen", "ScreenId", "dbo.Screen");
            RenameColumn(table: "dbo.FamilyMember", name: "CareerId", newName: "CareerTypeId");
            RenameColumn(table: "dbo.Student", name: "CircumstanceId", newName: "CircumstanceTypeId");
            RenameColumn(table: "dbo.Student", name: "ElectionId", newName: "ElectionTypeId");
            RenameIndex(table: "dbo.FamilyMember", name: "IX_CareerId", newName: "IX_CareerTypeId");
            RenameIndex(table: "dbo.Student", name: "IX_CircumstanceId", newName: "IX_CircumstanceTypeId");
            RenameIndex(table: "dbo.Student", name: "IX_ElectionId", newName: "IX_ElectionTypeId");
            AlterColumn("dbo.AccountGroup", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Account", "UserName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Account", "Password", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.UserInfo", "LastName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.UserInfo", "FirstName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.UserInfo", "Avatar", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.BirthInfo", "DateOfBirth", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.BirthInfo", "PlaceOfBirth", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.ContactInfo", "PhoneNumber", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.ContactInfo", "Email", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.ContactInfo", "Address", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.CareerType", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Student", "IdentificationNumber", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Student", "HightSchoolName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AchievementLevel", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AchievementPrize", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AchievementType", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CircumstanceType", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Class", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Department", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Faculty", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Program", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Document", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Document", "Url", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.DocumentType", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.ElectionType", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.EnrollmentArea", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.EnrollmentArea", "BonusingPoint", c => c.Double(nullable: false));
            AlterColumn("dbo.ConductType", "Level", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.LearningAbility", "Level", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.PositionType", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InsuranceType", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InsuranceDuration", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.PersonalInfo", "PermanentResidence", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Ethnic", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Nationality", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Religion", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.TalentType", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Subject", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.YouthGroupInfo", "PlaceOfJoinYouthGroup", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.RelationType", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.IdentityInfo", "IdentityNumber", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.IdentityInfo", "DateOfIssue", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.FunctionInScreen", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "Description", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("dbo.FunctionInScreen", "Area", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "ControllerName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "ActionName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Screen", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AdmissionNews", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.AdmissionNews", "ImageUrl", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.AdmissionNews", "Summary", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.AdmissionNews", "Content", c => c.String(nullable: false));
            AlterColumn("dbo.ErrorMsg", "Message", c => c.String(nullable: false));
            AlterColumn("dbo.Slide", "ImageUrl", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Slide", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Slide", "Content", c => c.String(nullable: false));
            AlterColumn("dbo.Slide", "Url", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.UniversityInfo", "UniversityName", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.UniversityInfo", "Address", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.UniversityInfo", "PhoneNumber", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("dbo.UniversityInfo", "Fax", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.UniversityInfo", "Email", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.UniversityInfo", "Summary", c => c.String(nullable: false));
            AlterColumn("dbo.UniversityInfo", "Website", c => c.String(nullable: false, maxLength: 255));
            AddForeignKey("dbo.Account", "UserInfoId", "dbo.UserInfo", "Id");
            AddForeignKey("dbo.Student", "UserInfoId", "dbo.UserInfo", "Id");
            AddForeignKey("dbo.Family", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.Achievement", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.Student", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.Document", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.Student", "EnrollmentAreaId", "dbo.EnrollmentArea", "Id");
            AddForeignKey("dbo.HighSchoolResult", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.HightSchoolPosition", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.Insurance", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.Student", "PersonalInfoId", "dbo.PersonalInfo", "Id");
            AddForeignKey("dbo.Talent", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.UniversityExamResult", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.Class", "DepartmentId", "dbo.Department", "Id");
            AddForeignKey("dbo.Class", "ProgramId", "dbo.Program", "Id");
            AddForeignKey("dbo.Department", "FacultyId", "dbo.Faculty", "Id");
            AddForeignKey("dbo.Document", "DocumentTypeId", "dbo.DocumentType", "Id");
            AddForeignKey("dbo.HighSchoolResult", "ConductTypeId", "dbo.ConductType", "Id");
            AddForeignKey("dbo.HighSchoolResult", "HightSchoolYearId", "dbo.HightSchoolYear", "Id");
            AddForeignKey("dbo.HighSchoolResult", "LearningAbilityId", "dbo.LearningAbility", "Id");
            AddForeignKey("dbo.HightSchoolPosition", "PositionTypeId", "dbo.PositionType", "Id");
            AddForeignKey("dbo.Insurance", "InsuranceTypeId", "dbo.InsuranceType", "Id");
            AddForeignKey("dbo.PersonalInfo", "EthnicId", "dbo.Ethnic", "Id");
            AddForeignKey("dbo.PersonalInfo", "NationalityId", "dbo.Nationality", "Id");
            AddForeignKey("dbo.PersonalInfo", "ReligionId", "dbo.Religion", "Id");
            AddForeignKey("dbo.Talent", "TalentTypeId", "dbo.TalentType", "Id");
            AddForeignKey("dbo.UniversityExamResult", "SubjectId", "dbo.Subject", "Id");
            AddForeignKey("dbo.Permission", "FunctionInScreenId", "dbo.FunctionInScreen", "Id");
            AddForeignKey("dbo.FunctionInScreen", "ScreenId", "dbo.Screen", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.FunctionInScreen", "ScreenId", "dbo.Screen");
            DropForeignKey("dbo.Permission", "FunctionInScreenId", "dbo.FunctionInScreen");
            DropForeignKey("dbo.UniversityExamResult", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.Talent", "TalentTypeId", "dbo.TalentType");
            DropForeignKey("dbo.PersonalInfo", "ReligionId", "dbo.Religion");
            DropForeignKey("dbo.PersonalInfo", "NationalityId", "dbo.Nationality");
            DropForeignKey("dbo.PersonalInfo", "EthnicId", "dbo.Ethnic");
            DropForeignKey("dbo.Insurance", "InsuranceTypeId", "dbo.InsuranceType");
            DropForeignKey("dbo.HightSchoolPosition", "PositionTypeId", "dbo.PositionType");
            DropForeignKey("dbo.HighSchoolResult", "LearningAbilityId", "dbo.LearningAbility");
            DropForeignKey("dbo.HighSchoolResult", "HightSchoolYearId", "dbo.HightSchoolYear");
            DropForeignKey("dbo.HighSchoolResult", "ConductTypeId", "dbo.ConductType");
            DropForeignKey("dbo.Document", "DocumentTypeId", "dbo.DocumentType");
            DropForeignKey("dbo.Department", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Class", "ProgramId", "dbo.Program");
            DropForeignKey("dbo.Class", "DepartmentId", "dbo.Department");
            DropForeignKey("dbo.UniversityExamResult", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Talent", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "PersonalInfoId", "dbo.PersonalInfo");
            DropForeignKey("dbo.Insurance", "StudentId", "dbo.Student");
            DropForeignKey("dbo.HightSchoolPosition", "StudentId", "dbo.Student");
            DropForeignKey("dbo.HighSchoolResult", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "EnrollmentAreaId", "dbo.EnrollmentArea");
            DropForeignKey("dbo.Document", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "ClassId", "dbo.Class");
            DropForeignKey("dbo.Achievement", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Family", "StudentId", "dbo.Student");
            DropForeignKey("dbo.Student", "UserInfoId", "dbo.UserInfo");
            DropForeignKey("dbo.Account", "UserInfoId", "dbo.UserInfo");
            AlterColumn("dbo.UniversityInfo", "Website", c => c.String(maxLength: 255));
            AlterColumn("dbo.UniversityInfo", "Summary", c => c.String());
            AlterColumn("dbo.UniversityInfo", "Email", c => c.String(maxLength: 50));
            AlterColumn("dbo.UniversityInfo", "Fax", c => c.String(maxLength: 30));
            AlterColumn("dbo.UniversityInfo", "PhoneNumber", c => c.String(maxLength: 15));
            AlterColumn("dbo.UniversityInfo", "Address", c => c.String(maxLength: 200));
            AlterColumn("dbo.UniversityInfo", "UniversityName", c => c.String(maxLength: 200));
            AlterColumn("dbo.Slide", "Url", c => c.String(maxLength: 255));
            AlterColumn("dbo.Slide", "Content", c => c.String());
            AlterColumn("dbo.Slide", "Title", c => c.String(maxLength: 200));
            AlterColumn("dbo.Slide", "ImageUrl", c => c.String(maxLength: 255));
            AlterColumn("dbo.ErrorMsg", "Message", c => c.String());
            AlterColumn("dbo.AdmissionNews", "Content", c => c.String());
            AlterColumn("dbo.AdmissionNews", "Summary", c => c.String(maxLength: 200));
            AlterColumn("dbo.AdmissionNews", "ImageUrl", c => c.String(maxLength: 255));
            AlterColumn("dbo.AdmissionNews", "Title", c => c.String(maxLength: 200));
            AlterColumn("dbo.Screen", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "ActionName", c => c.String(maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "ControllerName", c => c.String(maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "Area", c => c.String(maxLength: 50));
            AlterColumn("dbo.FunctionInScreen", "Description", c => c.String(maxLength: 500));
            AlterColumn("dbo.FunctionInScreen", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.IdentityInfo", "DateOfIssue", c => c.DateTime(precision: 0, storeType: "datetime2"));
            AlterColumn("dbo.IdentityInfo", "IdentityNumber", c => c.String(maxLength: 15));
            AlterColumn("dbo.RelationType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.YouthGroupInfo", "PlaceOfJoinYouthGroup", c => c.String(maxLength: 255));
            AlterColumn("dbo.Subject", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.TalentType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Religion", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Nationality", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Ethnic", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.PersonalInfo", "PermanentResidence", c => c.String(maxLength: 255));
            AlterColumn("dbo.InsuranceDuration", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.InsuranceType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.PositionType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.LearningAbility", "Level", c => c.String(maxLength: 50));
            AlterColumn("dbo.ConductType", "Level", c => c.String(maxLength: 50));
            AlterColumn("dbo.EnrollmentArea", "BonusingPoint", c => c.Double());
            AlterColumn("dbo.EnrollmentArea", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.ElectionType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.DocumentType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Document", "Url", c => c.String(maxLength: 255));
            AlterColumn("dbo.Document", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Program", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Faculty", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Department", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Class", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.CircumstanceType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.AchievementType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.AchievementPrize", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.AchievementLevel", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Student", "HightSchoolName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Student", "IdentificationNumber", c => c.String(maxLength: 50));
            AlterColumn("dbo.CareerType", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.ContactInfo", "Address", c => c.String(maxLength: 255));
            AlterColumn("dbo.ContactInfo", "Email", c => c.String(maxLength: 255));
            AlterColumn("dbo.ContactInfo", "PhoneNumber", c => c.String(maxLength: 15));
            AlterColumn("dbo.BirthInfo", "PlaceOfBirth", c => c.String(maxLength: 255));
            AlterColumn("dbo.BirthInfo", "DateOfBirth", c => c.DateTime(nullable: false, precision: 0, storeType: "datetime2"));
            AlterColumn("dbo.UserInfo", "Avatar", c => c.String(maxLength: 255));
            AlterColumn("dbo.UserInfo", "FirstName", c => c.String(maxLength: 50));
            AlterColumn("dbo.UserInfo", "LastName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Account", "Password", c => c.String(maxLength: 50));
            AlterColumn("dbo.Account", "UserName", c => c.String(maxLength: 50));
            AlterColumn("dbo.AccountGroup", "Name", c => c.String(maxLength: 50));
            RenameIndex(table: "dbo.Student", name: "IX_ElectionTypeId", newName: "IX_ElectionId");
            RenameIndex(table: "dbo.Student", name: "IX_CircumstanceTypeId", newName: "IX_CircumstanceId");
            RenameIndex(table: "dbo.FamilyMember", name: "IX_CareerTypeId", newName: "IX_CareerId");
            RenameColumn(table: "dbo.Student", name: "ElectionTypeId", newName: "ElectionId");
            RenameColumn(table: "dbo.Student", name: "CircumstanceTypeId", newName: "CircumstanceId");
            RenameColumn(table: "dbo.FamilyMember", name: "CareerTypeId", newName: "CareerId");
            AddForeignKey("dbo.FunctionInScreen", "ScreenId", "dbo.Screen", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Permission", "FunctionInScreenId", "dbo.FunctionInScreen", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UniversityExamResult", "SubjectId", "dbo.Subject", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Talent", "TalentTypeId", "dbo.TalentType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PersonalInfo", "ReligionId", "dbo.Religion", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PersonalInfo", "NationalityId", "dbo.Nationality", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PersonalInfo", "EthnicId", "dbo.Ethnic", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Insurance", "InsuranceTypeId", "dbo.InsuranceType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HightSchoolPosition", "PositionTypeId", "dbo.PositionType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HighSchoolResult", "LearningAbilityId", "dbo.LearningAbility", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HighSchoolResult", "HightSchoolYearId", "dbo.HightSchoolYear", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HighSchoolResult", "ConductTypeId", "dbo.ConductType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Document", "DocumentTypeId", "dbo.DocumentType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Department", "FacultyId", "dbo.Faculty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Class", "ProgramId", "dbo.Program", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Class", "DepartmentId", "dbo.Department", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UniversityExamResult", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Talent", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "PersonalInfoId", "dbo.PersonalInfo", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Insurance", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HightSchoolPosition", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HighSchoolResult", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "EnrollmentAreaId", "dbo.EnrollmentArea", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Document", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "ClassId", "dbo.Class", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Achievement", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Family", "StudentId", "dbo.Student", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "UserInfoId", "dbo.UserInfo", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Account", "UserInfoId", "dbo.UserInfo", "Id", cascadeDelete: true);
        }
    }
}
